### ISSUE TITLE
AWS credentials

### ISSUE THREAD

**Issue by sp-joseluis-ledesma** [giantswarm/etcd-backup#26]
Hi!
  I 've seen this project do not make use of the standard way of getting AWS credentials, that the aws-sdk-go library already provides (https://docs.aws.amazon.com/sdk-for-go/api/aws/session/), this is.
 - Use the environment variables: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN
- use .aws/credentials
- use the instanced metadata to gather the Instance Profile credentials.

 I can make a PR with this change, maintaining backward compatibility with the current env variables you use (ETCDBACKUP_AWS_ACCESS_KEY and ETCDBACKUP_AWS_SECRET_KEY) if this is ok for you.

**Comment by debojitkakoti** [comment]
Instead of AWS_SESSION_TOKEN, I think it is better to use role, probably through kube2iam,
Because if AWS_SECRET_ACCESS_KEY contains '/', it is giving error .

**Comment by kopiczko** [comment]
This repository is going to be archived as we don't maintain it anymore. We are now doing etcd backups using https://github.com/giantswarm/etcd-backup-operator. Feel free to open an issue there or fork this repository.
